# Generated by Django 5.0.4 on 2024-05-01 15:03

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('src', models.TextField()),
                ('lugar', models.CharField(max_length=256)),
                ('coordenadas', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comentador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('comentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_TeVeO.comentador')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_TeVeO.camara')),
            ],
        ),
    ]
