# Generated by Django 5.0.4 on 2024-05-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentador',
            old_name='nome',
            new_name='name',
        ),
    ]
