# Generated by Django 5.0.4 on 2024-05-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0002_rename_nome_comentador_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camara',
            name='num_comentarios',
            field=models.IntegerField(default=0),
        ),
    ]
