# Generated by Django 5.0.4 on 2024-05-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0003_camara_num_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_gusta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_TeVeO.camara')),
            ],
        ),
    ]
