# Generated by Django 5.0.4 on 2024-05-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentador',
            name='letra_size',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='comentador',
            name='letra_tipo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='comentador',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
