# Generated by Django 5.0.4 on 2024-05-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0005_comentador_letra_size_comentador_letra_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentador',
            name='name',
            field=models.CharField(default='Anonimo', max_length=100),
        ),
    ]
