# Generated by Django 5.0.4 on 2024-05-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0006_alter_comentador_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentador',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
