# Generated by Django 5.0.4 on 2024-05-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TeVeO', '0007_alter_comentador_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentador',
            field=models.CharField(max_length=100),
        ),
    ]
